### ISSUE TITLE
add normalization functions?

### ISSUE THREAD

**Issue by maximromanov** [OpenITI/openiti#1]

**Comment by pverkind** [comment]
Hi Maxim, it contains 3 normalization functions: 

>>> openiti.helper.ara.normalize_ara_heavy("قهوة")
'قهوه'

>>> openiti.helper.ara.normalize_ara_light("قهوة")
'قهوة'

>>> openiti.helper.ara.normalize('AlphaBet', [("A", "a"), ("B", "b")])
'alphabet'

See the [documentation](https://openiti.readthedocs.io/en/latest/source/usermanual.html#openiti.helper.ara.normalize_ara_heavy)

Do you want anything else?

**Comment by maximromanov** [comment]
Awesome! I could not find documentation :) I am working on some functions
that would be nice to have in the library. Perhaps, we might want to
discuss this at some point?

**Comment by pverkind** [comment]
Yes please!

Maxim Romanov <notifications@github.com> schrieb am Fr., 10. Apr. 2020,
9:49 vorm.:

> Awesome! I could not find documentation :) I am working on some functions
> that would be nice to have in the library. Perhaps, we might want to
> discuss this at some point?
>
