### ISSUE TITLE
Reflow parameter in readYML

### ISSUE THREAD

**Issue by raffazizzi** [OpenITI/OpenITI#2]
`openiti.helper.yml.readYML` does not pass `reflow` to `ymlToDic`. See [line 146](https://github.com/OpenITI/openiti/blob/32a33daa44753b668ab21f92d4ec13f8f618254f/openiti/helper/yml.py#L146). It should probably be:

`return ymlToDic(s, reflow=reflow, yml_fp=fp)`

**Comment by pverkind** [comment]
Thanks! Will be fixed in v0.1.5.9
